application:
  temp:
    capacity: 20
    command: vcgencmd measure_temp
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
info:
  appName: Raspi Executor
  description: An app to run actions on raspi using http
  version: 1.0
logging:
  level:
    com.netflix.eureka: off
    com.netflix.discovery: off
  file:
    path: /var/log/raspi-exe.log
management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"
server:
  port: 8888
  address: 0.0.0.0
spring:
  application:
    name: Raspi Executor
  banner:
    image:
      location: classpath:banner.txt
  cloud:
    config:
      server:
        prefix: /configuration
        git:
          uri: https://github.com/ambiguous1991/configuration-properties
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs.html