server:
  port: 36666
  address: 0.0.0.0
spring:
  banner:
    image:
      location: classpath:banner.txt
  application:
    name: Raspi Executor
  cloud:
    config:
      server:
        prefix: /configuration
        git:
          uri: https://github.com/ambiguous1991/configuration-properties
info:
  appName: Raspi Executor
  description: An app to run actions on raspi using http
  version: 1.0
springdoc:
  swagger-ui:
    path: /docs.html
  api-docs:
    path: /api-docss
management:
  endpoints:
    web:
      cors:
        allowed-origins: "*"